import React from 'react'
import Header from '../components/Header'
import axios from 'axios';
import react, { useState,useEffect } from 'react'
import Router from 'next/router'
import Link from 'next/link'
import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/Footer';
import Contact from '../components/Contact';
import Subscribe from '../components/Subscribe';
import { PlusIcon,ChevronDoubleLeftIcon } from "@heroicons/react/solid";


const aboutus = () => {
  return (
    <div>
         <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      


      <Header />

      <Link href="/">
            <div className='flex flex-row cursor-pointer ml-6'>
        <ChevronDoubleLeftIcon width={30}/><span className='my-2'>Back</span>
        </div>
            </Link>



      <div className='h-full w-full'>
          <div className='flex flex-col justify-center'>
          <h1 className='text-3xl text-center my-12'> About Us</h1>
          <p className='w-7/12 mx-[auto] py-6 text-justify'>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti, modi quibusdam provident ratione asperiores molestiae sequi, sapiente porro molestias nesciunt, hic magni id earum. Alias minus voluptatum quasi suscipit vel?
Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quod beatae consectetur ipsam quidem voluptatem molestiae culpa libero animi corporis aspernatur, est repellat sapiente mollitia assumenda in voluptates dignissimos dicta quas.
Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia praesentium dignissimos minima soluta, obcaecati atque optio temporibus similique eligendi repudiandae, reiciendis facilis recusandae ipsa quae inventore! Ab, ut! Modi, nemo.
          </p>
          </div>
          </div>

          <hr className='w-8/12 mx-[auto]'/>
          <p className='w-7/12 mx-[auto] py-6 mb-6  text-justify'>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti, modi quibusdam provident ratione asperiores molestiae sequi, sapiente porro molestias nesciunt, hic magni id earum. Alias minus voluptatum quasi suscipit vel?
          </p>
       
        
        {/* <Contact /> */}
        {/* <Footer /> */}

        <Subscribe />
            <Footer />
        </div>
  )
}

export default aboutus