import React from 'react'
import Header from '../components/Header'
import axios from 'axios';
import react, { useState,useEffect } from 'react'
import Router from 'next/router'
import Link from 'next/link'
import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/Footer';
import Contact from '../components/Contact';
import Subscribe from '../components/Subscribe';
import { PlusIcon,ChevronDoubleLeftIcon } from "@heroicons/react/solid";


const aboutus = () => {
  return (
    <div>
         <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      


      <Header />

      <Link href="/">
            <div className='flex flex-row cursor-pointer ml-6'>
        <ChevronDoubleLeftIcon width={30}/><span className='my-2'>Back</span>
        </div>
            </Link>



      <div className='h-full w-full'>
          <div className='flex flex-col justify-center'>
          <h1 className='text-3xl text-center my-12'> About Us</h1>
          <p className='w-7/12 mx-[auto] py-6 text-justify'>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti, modi quibusdam provident ratione asperiores molestiae sequi, sapiente porro molestias nesciunt, hic magni id earum. Alias minus voluptatum quasi suscipit vel?
Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quod beatae consectetur ipsam quidem voluptatem molestiae culpa libero animi corporis aspernatur, est repellat sapiente mollitia assumenda in voluptates dignissimos dicta quas.
Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia praesentium dignissimos minima soluta, obcaecati atque optio temporibus similique eligendi repudiandae, reiciendis facilis recusandae ipsa quae inventore! Ab, ut! Modi, nemo.
          </p>
          </div>
          </div>

          <hr className='w-8/12 mx-[auto]'/>
          <p className='w-7/12 mx-[auto] py-6 mb-6  text-justify'>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti, modi quibusdam provident ratione asperiores molestiae sequi, sapiente porro molestias nesciunt, hic magni id earum. Alias minus voluptatum quasi suscipit vel?
          </p>
       
        
        {/* <Contact /> */}
        {/* <Footer /> */}

        {/* <Subscribe /> */}
        <div className='w-full bg-[black] flex flex-row'>


                <div className='w-5/12  h-[auto]'>
                <div className=' bg-[black] text-white '>
        <h2 className='text-3xl text-center py-6'>Contact Us</h2>
        <div className='flex flex-col w-full ml-[6rem] pt-12 ' >
            <div className='flex flex-row w-full'>
                <div className='w-6/12'><label>FirstName</label>
                <br/>
                <input
                className='mb-4 py-1 pl-2 text-black w-full'
                 />
                </div>



                <div className='ml-12 w-6/12'><label>LastName</label>
                <br/>
                <input
                className='mb-4 py-1 px-2 text-black w-full' />
                </div>



                </div>


                <div className='flex flex-col w-full'>
                    <label>Enter Your Email</label>
                    <input 
                    className='mb-4 py-1 px-2 text-black'/>

                    <label>Enter your Subject</label>
                    <input 
                    className='mb-4 py-2 px-2 text-black'/>

                    <label>Enter Your Message</label>
                    <textarea className='resize-none h-[10rem] pt-2 px-2 text-black'></textarea>

                </div>



                <button className='mt-2 mb-6 bg-[none] w-16 border-2 border-white text-white'>Send</button>

                
            </div>
            </div>
                </div>



                <div className='ml-[10rem] w-5/12'>
                    <div className='bg-black h-[30rem] flex flex-col items-center mt-6'>
                    <h2 className='text-4xl text-white flex justify-center'>JOIN OUR MAILING LIST</h2>
        <h4 className='text-xl text-white mb-6'>And Never Miss An Update</h4>


        <div className='flex flex-col justify-center text-white w-8/12 text-center'>
        <label required>Enter your Email Here</label>
        <input 
        placeholder="Email"
        className='outline-white border-2 border-white mt-6 w-12/12 h-12 text-black py-[auto] pl-4 pr-4'
        />
        <button className='outline-white border-2 border-white mt-6 w-12/12 h-12'>Subscribe </button>
            </div>


                    </div>
                </div>

              
            </div>
            <Footer />
        </div>
  )
}

export default aboutus