import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/Footer'
import Contact from '../components/Contact'
import HomeNavbar from '../components/HomeNavbar'
import { PlusIcon } from "@heroicons/react/solid";
import axios from 'axios';
import { useState,useEffect } from 'react'
import Router from 'next/router'
import Link from 'next/link'
import NewProduct from '../components/NewProduct'
import Subscribe from '../components/Subscribe'
import LoginModal from '../components/LoginModal'
import { UserIcon, ShoppingCartIcon } from "@heroicons/react/solid";





export default function Home() {
    const[products, setProducts] = useState()
    const[newItem, setNewItem] = useState()
    const [newProducts, setNewProducts] = useState()
    const [close, setClose] = useState(false);
    const random = Math.floor(Math.random() * 10);
  
  
  
  
    useEffect(() => {
      async function showCase(){
    try{
      const response = await axios.get('https://fakestoreapi.com/products?limit=3')
      console.log(response.data)
      setProducts(response.data)
    }catch(error){
      console.log(error)
    }
      }

      async function cart(){
        try{
          fetch('https://fakestoreapi.com/carts/5')
            .then(res=>res.json())
            .then(json=>console.log(json))
        }catch(error){
          console.log(error)
        }
      }
      // const showCase = () => {
      //   try {
      //     fetch('https://fakestoreapi.com/products?limit=3')
      //     .then(res=>res.json())
      //     // .then(json=>console.log(json))
      //     .then(json=> {
      //       setProducts(json)
      //     })
      //   } catch (error) {
      //     console.log(error)
      //   }
      // }
    //   async function getNewProducts() {
    //     try {
    //         const res = await axios.get(`https://fakestoreapi.com/products/${random}`)
    //             console.log(res.data)
                
    //     } catch (error) {
    //         console.log(error)
    //     }return{
    //         props:{
    //             newProducts
    //         }   
    //     }
    // }

      showCase()
      // getNewProducts()
      cart()
    },[])
  
    // useEffect(() => {
    //   const newArrivals = () => {
    //     try{
    //       fetch(`https://fakestoreapi.com/products/${random}`)
    //       .then(res =>res.json())
         
    //       .then(json => {
    //         console.log(json)
    //       })
    //     }catch(error){
    //       console.log(error)
    //     }
    //     return{
    //       props:{
    //         newItem
    //       }
    //     }
    //   }
    //   newArrivals()
    // },[])
  
  
  
    function closeModal () {
      setClose(false);
    
    }
  
  
  
  
  
    
  
  
    const openStore = () => {
      Router.push('/store')
    }
  
    


  return (
    <div className='h-screen w-full'>
          <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <div className='h-[4rem] pl-6  text-[white] bg-[blue] flex items-center '>
        <h1 className='w-9/12'>Peter&apos;s Place</h1>


        <div className='flex hidden flex-wrap lg:flex'>
            <Link href='/store'><span className='mx-6'>Shop</span></Link>
        
           <Link href='/about'><span className='mx-6'>About</span></Link>
            <span className='flex'><UserIcon width={20}/> Login</span>
            <span className='ml-6'><ShoppingCartIcon width={20} height={30}/></span>
        </div>

        <button className='flex lg:hidden'>[-__-]</button>
        </div>

<div className="h-[100vh] flex items-center justify-center bg-[url('../assets/images/838.jpg')] bg-no-repeat bg-cover">
        <div>
        <h1 className='text-center text-white text-3xl mb-6'>Peter&apos;s Place</h1>
        <button className='bg-[blue]  w-[12rem] text-white h-12' onClick={openStore}>Shop</button>
        </div>
       
        </div>


        <NewProduct newItem={newProducts} />


        <div className=' mt-4 justify-center'>

          <h1 className='text-2xl text-center'>The Best deals on Offer!</h1>


          <div className='flex-wrap flex-row flex justify-center'>
           {products && products.map(product => (
              <Link href="/products/[id]" as={`/products/${product.id}`} key={product.id}>


              <div className='h-[30rem] w-11/12 lg:w-[25rem] lg:mr-6 my-6 hover:border-2 border-[blue] cursor-pointer' key={product.id}>
                  <div className='flex flex-col h-3/4  py-[auto] items-center justify-center cursor-pointer'><img src={product.image} height={200} width={150}/></div>
                <div className='flex flex-col jusitfy-around w-11/12 mx-[auto]'>
                    {product.title}
                    <br/>
                    <p className='font-bold my-[auto]'>{product.price}$</p>
                    </div>
                </div>
                </Link>
           ))} 

           </div>
           
           </div>



           <Subscribe />

{/* <Contact /> */}
<Footer />


    </div>
  )
}

