import Head from "next/head";
import Image from "next/image";
import Footer from "../components/Footer";
import Contact from "../components/Contact";
import HomeNavbar from "../components/HomeNavbar";
import { PlusIcon } from "@heroicons/react/solid";
import axios from "axios";
import { useState, useEffect } from "react";
import Router from "next/router";
import Link from "next/link";
import NewProduct from "../components/NewProduct";
import Subscribe from "../components/Subscribe";
import LoginModal from "../components/LoginModal";
import { UserIcon, ShoppingCartIcon } from "@heroicons/react/solid";
import { useSelector } from "react-redux";
import { SpinnerCircular } from "spinners-react";
import Showcase from "../components/Showcase";

export default function Home() {
  const [products, setProducts] = useState(null);
  const [newItem, setNewItem] = useState();
  const [newProducts, setNewProducts] = useState();
  const [close, setClose] = useState(false);
  const cart = useSelector((state) => state.cart);
  const [loader, setLoader] = useState(false);

  const getItemsCount = () => {
    return cart.reduce((accumulator, item) => accumulator + item.quantity, 0);
  };

  // const random = Math.floor(Math.random() * 10);

  useEffect(() => {
    setLoader(false);
  });

  useEffect(() => {
    const random = Math.floor(Math.random() * 10);
    console.log(random);

    async function showCase() {
      try {
        const response = await axios.get(
          "https://fakestoreapi.com/products?limit=3"
        );
        console.log(response.data);
        setProducts(response.data);
        setLoader(true);
      } catch (error) {
        console.log(error);
      }
    }

    async function newItem() {
      try {
        const response = await axios.get(
          `https://fakestoreapi.com/products/${random}`
        );
        console.log(response.data);
        setNewItem(response.data);
      } catch (error) {
        console.log(error);
      }
    }

    showCase();

    newItem();
  }, []);

  function closeModal() {
    setClose(false);
  }

  const openStore = () => {
    Router.push("/store");
  };

  return (
    <div className="h-screen w-full">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-full border-2 border-[blue] h-[4rem] text-[white] bg-[blue]">
        <div className="flex  justify-around h-full">
          <Link href="/">
            <div className="lg:w-8/12  cursor-pointer flex items-center">
              <h1 className="w-max hover:border-b-2 hover:border-[white]">
                Peter&apos;s Place
              </h1>
            </div>
          </Link>

          <div className="flex flex-row items-center">
            <Link href="/about">
              <span className=" mx-4 lg:mx-12 hover:border-b-2 hover:border-[white] cursor-pointer">
                About
              </span>
            </Link>
            <Link href="/store">
              <span className=" mr-4 lg:mr-8 hover:border-b-2 hover:border-[white] cursor-pointer">
                Shop
              </span>
            </Link>
            <Link href="/cart">
              <span className="ml-0 flex lg:ml-6 hover:border-b-2 hover:border-[white] cursor-pointer">
                <ShoppingCartIcon width={20} height={30} />
                <sup className="pt-2">{getItemsCount()}</sup>
              </span>
            </Link>
          </div>
        </div>
      </div>

      <div className="h-[100vh] flex items-center justify-center bg-[url('../assets/images/838.jpg')] bg-no-repeat bg-cover">
        <div>
          <h1 className="text-center text-white text-3xl mb-6">
            Peter&apos;s Place
          </h1>
          <button
            className="bg-[blue]  w-[12rem] text-white h-12"
            onClick={openStore}
          >
            Shop
          </button>
        </div>
      </div>

      <div className=" mt-4 justify-center">
        <h1 className="text-2xl text-center ">
          The Best deals on Offer!{" "}
          <hr className="w-8/12 lg:w-3/12 border-[blue]  mx-auto"></hr>
        </h1>

        <Showcase products={products} loader={loader} openStore={openStore} />

        <div className="flex flex-col items-center my-6 ">
          <button
            className="w-6/12 lg:w-2/12 p-4 border-red border-2 bg-[blue] text-white"
            onClick={openStore}
          >
            Shop
          </button>
        </div>
      </div>

      <Subscribe />

      <Footer />
    </div>
  );
}
