import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/Footer'
import Contact from '../components/Contact'
import HomeNavbar from '../components/HomeNavbar'
import { PlusIcon } from "@heroicons/react/solid";
import axios from 'axios';
import { useState,useEffect } from 'react'
import Router from 'next/router'
import Link from 'next/link'
import NewProduct from '../components/NewProduct'
import Subscribe from '../components/Subscribe'
import LoginModal from '../components/LoginModal'
import { UserIcon, ShoppingCartIcon } from "@heroicons/react/solid";



export default function Home() {
  const[products, setProducts] = useState()
  const[newItem, setNewItem] = useState()
  const [newProducts, setNewProducts] = useState()
  const [close, setClose] = useState(false);




  useEffect(() => {
    const showCase = () => {
      try {
        fetch('https://fakestoreapi.com/products?limit=3')
        .then(res=>res.json())
        // .then(json=>console.log(json))
        .then(json=> {
          setProducts(json)
        })
      } catch (error) {
        console.log(error)
      }
    }
    showCase()
  })


  function closeModal () {
    setClose(false);
  
  }





  


  const openStore = () => {
    Router.push('/store')
  }
  

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <LoginModal visible={close} closeModal={closeModal} />


     {/* <HomeNavbar /> */}


     <div className='h-[4rem] pl-6  text-[white] bg-[blue] flex items-center '>
        <h1 className='w-9/12'>E-commerce</h1>


        <div className='flex flex-wrap '>
            <a href='/store'><span className='mx-6'>Shop</span></a>
           <a href='/aboutus'><span className='mx-6'>About</span> </a>
            <span className='flex'><UserIcon width={20}/> Login</span>
            <span className='ml-6'><ShoppingCartIcon width={20} height={30}/></span>
        </div>
        </div>


      <div className="h-[100vh] flex items-center justify-center bg-[url('../assets/images/838.jpg')] bg-no-repeat bg-cover">
        <div>
        <h1 className='text-center text-white text-3xl mb-6'>E-commerce</h1>
        <button className='bg-[black] border-[white] border-2 w-[12rem] text-white h-12' onClick={openStore}>Shop</button>
        </div>
       
        </div>



       <NewProduct />



          



        <div className=' mt-4 justify-center'>

          <h1 className='text-2xl text-center'>The Best deals on Offer!</h1>


          <div className='flex-wrap flex-row flex justify-center'>
           {products && products.map(product => (
              <Link href="/products/[id]" as={`/products/${product.id}`} key={product.id}>


              <div className='h-[30rem]  w-[25rem] mr-6 my-6 hover:border-2 border-[blue] cursor-pointer' key={product.id}>
                  <div className='flex flex-col h-3/4  py-[auto] items-center justify-center cursor-pointer'><img src={product.image} height={200} width={150}/></div>
                <div className='flex flex-col jusitfy-around w-11/12 mx-[auto]'>
                    {product.title}
                    <br/>
                    <p className='font-bold my-[auto]'>{product.price}$</p>
                    </div>
                </div>
                </Link>
           ))} 


         



          {/* <div className='h-[30rem] border-2 border-[royalblue] w-[25rem] mr-6 my-6'></div> */}



          {/* <div className='h-[30rem] border-2 border-[royalblue] w-[25rem]  my-6'>
            {products && products.map(product => (
              <div key={product.id}>
                <img src={product.image} />
                </div>
            ))}


       
            </div> */}

          </div>


          <Link href='/store'>

          <button className='bg-[blue] text-[white] h-12 w-[8rem] justify-center mx-[45vw] mb-6' >Shop Now</button>


          </Link>


          </div>

          <Subscribe />

          {/* <Contact /> */}
        <Footer />
    </div>
  )
}
